/**
 * Type declarations for blog-database-github-client
 */

export interface BlogClientConfig {
  repo: string;
  branch: string;
  project: string;
  cacheTtl?: number;
  useLocalStorage?: boolean;
}

export interface PostMeta {
  slug: string;
  title: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  metatags?: string[];
  [key: string]: any; // Catch-all for other front-matter
}

export interface PostsPage {
  page: number;
  totalPosts: number;
  items: PostMeta[];
}

export interface Post {
  slug: string;
  frontmatter: PostMeta;
  content: string; // Markdown body
}

export interface PaginationIndex {
  totalPosts: number;
  totalPages: number;
  pages: string[];
  generatedAt: string;
}

// ── Book types ────────────────────────────────────────────────────────────────

export interface BookMeta {
  slug: string;
  name: string;
  description?: string;
}

export interface BookTreeItem {
  type: 'file' | 'folder';
  name: string;
  path: string;
  description?: string;
  items?: BookTreeItem[]; // only present when type === 'folder'
}

export interface BookTree {
  name: string;
  slug: string;
  description?: string;
  type: 'book';
  items: BookTreeItem[];
}

export interface BookMap {
  slug: string;
  name: string;
  description?: string;
  type: 'book';
  generatedAt: string;
  tree: BookTree;
}

export interface BookFile {
  bookSlug: string;
  path: string;
  frontmatter: Record<string, any>;
  content: string;
}

export interface BooksIndex {
  books: BookMeta[];
  generatedAt: string;
}

// ── Client ────────────────────────────────────────────────────────────────────

export interface BlogClient {
  /**
   * Fetch a single page of post metadata.
   * @param page 1-based page number (default 1)
   */
  getPosts(page?: number): Promise<PostsPage>;
  
  /**
   * Fetch all posts across all pages.
   */
  getAllPosts(): Promise<PostMeta[]>;
  
  /**
   * Fetch full content of a single post by slug.
   */
  getPost(slug: string): Promise<Post>;
  
  /**
   * Client-side search across all posts.
   */
  search(query: string): Promise<PostMeta[]>;
  
  /**
   * Return the cached pagination index without refetching.
   */
  getIndex(): PaginationIndex | null;
  
  /**
   * Clear all cached data.
   */
  clearCache(): void;

  /**
   * List all books in the project.
   * Reads from books/index.json generated by the CMS generate step.
   */
  getBooks(): Promise<BookMeta[]>;

  /**
   * Fetch the full file/folder tree for a book.
   * Reads from books/<bookSlug>/map.json generated by the CMS generate step.
   */
  getBookMap(bookSlug: string): Promise<BookMap>;

  /**
   * Fetch a single book file's content and front-matter.
   * @param bookSlug  The book slug
   * @param filePath  Path relative to the book root (e.g. "concepts/overview.md")
   */
  getBookFile(bookSlug: string, filePath: string): Promise<BookFile>;
}

/**
 * Create a blog client instance.
 */
export function createBlogClient(config: BlogClientConfig): BlogClient;

// Internal Utils (optional to export types, but good practice if explicitly exported from index.js)
export function buildUrl(config: BlogClientConfig, filePath: string): string;
export function fetchJson<T = any>(url: string, options?: { signal?: AbortSignal, timeout?: number }): Promise<T>;
export function fetchMarkdown(url: string, options?: { signal?: AbortSignal, timeout?: number }): Promise<{ frontmatter: Record<string, any>; content: string }>;
